(()=>{'use strict';const $=id=>document.getElementById(id),status=$('status'),viewer=$('viewer'),hint=$('dropHint');if(!window.THREE||!THREE.GLTFLoader){status.textContent='Three.js failed to load.';return}
const renderer=new THREE.WebGLRenderer({antialias:false,powerPreference:'low-power'});renderer.setPixelRatio(Math.min(devicePixelRatio||1,1.5));viewer.appendChild(renderer.domElement);
const scene=new THREE.Scene();scene.background=new THREE.Color(0x0b0d10);const camera=new THREE.PerspectiveCamera(40,1,.0001,100);const hemi=new THREE.HemisphereLight(0xffffff,0x303030,1.8);scene.add(hemi);const light=new THREE.DirectionalLight(0xffffff,2.5);light.position.set(1,2,2);scene.add(light);const fill=new THREE.DirectionalLight(0xffffff,1.2);fill.position.set(-2,1,-2);scene.add(fill);
const orbit=new THREE.OrbitControls(camera,renderer.domElement);orbit.enableDamping=false;orbit.addEventListener('change',render);
let model=null,helper=null,bones=[],selected=null,box=null,rest=new Map(),raf=0,last=0,meshCount=0,wiggleWasOn=false;
function render(){renderer.render(scene,camera)}
function resize(){renderer.setSize(viewer.clientWidth,viewer.clientHeight,false);camera.aspect=viewer.clientWidth/viewer.clientHeight;camera.updateProjectionMatrix();render()}addEventListener('resize',resize);
function frame(){if(!box)return;const c=box.getCenter(new THREE.Vector3()),s=Math.max(box.getSize(new THREE.Vector3()).length(),.1);orbit.target.copy(c);camera.position.copy(c).add(new THREE.Vector3(s*.65,s*.42,s*.9));camera.near=.0001;camera.far=Math.max(100,s*50);camera.updateProjectionMatrix();orbit.update();render()}
function movable(b){return !/Metatarsal|Heel|Tip|Leg/.test(b.name)}
function buildUI(){const sel=$('joint');sel.innerHTML='';bones.forEach(b=>{const o=document.createElement('option');o.value=b.uuid;o.textContent=b.name+(movable(b)?'':' [STATIC/END]');sel.appendChild(o)});if(bones.length)pick(bones[0]);}
function pick(uuid){selected=bones.find(b=>b.uuid===uuid)||null;if(!selected)return;$('joint').value=selected.uuid;sync()}
$('joint').addEventListener('change',e=>pick(e.target.value));
function sync(){if(!selected)return;for(const a of ['x','y','z'])$(a+'v').value=(selected.rotation[a]*180/Math.PI).toFixed(2)}
const rot=$('rot');function commitSelected(){if(selected)rest.set(selected,selected.quaternion.clone())}\nfunction change(a,d){if(!selected)return;selected.rotation[a]+=d*Math.PI/180;commitSelected();sync();render()}
for(const a of ['x','y','z']){const row=document.createElement('div');row.className='coord';row.innerHTML='<span class="axis">'+a.toUpperCase()+'</span><button class="nudge">−</button><input id="'+a+'v" type="number" step="0.1"><button class="nudge">+</button>';rot.appendChild(row);const bs=row.querySelectorAll('button');bs[0].onclick=()=>change(a,-Number($('step').value));bs[1].onclick=()=>change(a,Number($('step').value));$(a+'v').onchange=e=>{if(selected&&Number.isFinite(+e.target.value)){selected.rotation[a]=(+e.target.value)*Math.PI/180;commitSelected();render()}}}
function reset(){rest.forEach((q,b)=>{b.quaternion.copy(q)});sync();render();status.textContent='Rest pose restored.'}$('reset').onclick=reset;$('frame').onclick=frame;
function mats(){if(!model)return;const wire=$('wire').checked,op=+$('opacity').value;model.traverse(o=>{if(o.isMesh){const ms=Array.isArray(o.material)?o.material:[o.material];ms.forEach(m=>{m.wireframe=wire;m.transparent=op<.999;m.opacity=op;m.depthWrite=op>.98;m.needsUpdate=true})}});render()}$('wire').onchange=mats;$('opacity').oninput=mats;$('skeleton').onchange=()=>{if(helper)helper.visible=$('skeleton').checked;render()};
function animate(t){raf=requestAnimationFrame(animate);const on=$('wiggle').checked;if(!on){if(wiggleWasOn){rest.forEach((q,b)=>b.quaternion.copy(q));wiggleWasOn=false;sync();render()}return;}wiggleWasOn=true;const time=t*.001*+$('speed').value,amp=+$('amount').value*Math.PI/180;for(const b of bones){const base=rest.get(b);if(!base)continue;b.quaternion.copy(base);if(!movable(b)||!/Hallux|Index|Middle|Ring|Pinky/.test(b.name))continue;const side=b.name.startsWith('Left')?0:.35;const toe=b.name.includes('Hallux')?0:b.name.includes('Index')?.45:b.name.includes('Middle')?.9:b.name.includes('Ring')?1.35:1.8;const phase=time*4+toe+side;const factor=/Proximal/.test(b.name)?1:/Middle/.test(b.name)?.65:.42;const q=new THREE.Quaternion().setFromAxisAngle(new THREE.Vector3(1,0,0),Math.sin(phase)*amp*factor);b.quaternion.multiply(q)}if(selected)sync();render()}animate(0);
$('file').addEventListener('change',e=>{const f=e.target.files[0];if(!f)return;status.textContent='Loading rig…';const r=new FileReader();r.onload=()=>new THREE.GLTFLoader().parse(r.result,'',g=>{if(model)scene.remove(model);if(helper)scene.remove(helper);model=g.scene;scene.add(model);bones=[];meshCount=0;rest.clear();model.traverse(o=>{if(o.isBone){bones.push(o);rest.set(o,o.quaternion.clone())}if(o.isMesh){meshCount++;o.visible=true;o.frustumCulled=false;const ms=Array.isArray(o.material)?o.material:[o.material];ms.forEach(m=>{
 m.side=THREE.DoubleSide;
 m.map=null;m.normalMap=null;m.roughnessMap=null;m.metalnessMap=null;m.aoMap=null;m.emissiveMap=null;
 if(m.color)m.color.setRGB(0.82,0.56,0.43);
 if(m.emissive)m.emissive.setRGB(0.16,0.08,0.05);
 if('roughness' in m)m.roughness=.72;
 if('metalness' in m)m.metalness=0;
 m.transparent=false;m.opacity=1;m.depthWrite=true;m.needsUpdate=true
})}});box=new THREE.Box3().setFromObject(model);if(box.isEmpty()||!isFinite(box.min.x)){box=new THREE.Box3().setFromCenterAndSize(new THREE.Vector3(0,0,0),new THREE.Vector3(1,1,1))}helper=new THREE.SkeletonHelper(model);helper.visible=$('skeleton').checked;scene.add(helper);hint.style.display='none';frame();buildUI();mats();status.textContent='Loaded '+meshCount+' mesh(es), '+bones.length+' bones. Bright test material enabled.';render()},err=>status.textContent='GLB error: '+err.message);r.readAsArrayBuffer(f)});
renderer.domElement.addEventListener('webglcontextlost',e=>{e.preventDefault();status.textContent='WebGL context lost. Reload the page.'});resize();status.textContent='Ready. Load G9_Feminine_Feet_ProductionRig_v1.glb.';render()})();